# Base Dockerfile
FROM ubuntu:22.04
LABEL maintainer="youremail@example.com"

# Update and install Python and pip
RUN apt-get update -y && \
    apt-get install -y python3 python3-pip

# Copy only the requirements file first to cache dependencies
COPY ./requirements.txt /app/requirements.txt
WORKDIR /app

# Install dependencies
RUN pip3 install -r requirements.txt

# Copy all application files
COPY . /app

# Run the Connexion application
ENTRYPOINT ["python3"]
CMD ["app.py"]
