openapi: 3.0.0
info:
  version: 1.0.0
  title: 'Calendar Task Manager'
  description: Calendar task creation, viewing, and completion
paths:
  /tasks:
    get:
      description: Returns a list of tasks 
      operationId: app.tasks
      responses:
        '200':
          description: Successful response
        '400':
          description: Tasks not found

  /create:
    post:
      description: Create a task (specify day, time, and description)
      operationId: app.create
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - uuid
                - task_name
                - due_date
                - task_description  # Included as a required field
                - task_difficulty    # Included as a required field
              properties:
                uuid:
                  type: string
                  format: uuid
                  description: UUID for the task
                task_name:
                  type: string
                  description: Name of the task
                due_date:
                  type: string
                  format: date-time
                  description: Due date and time for the task
                task_description:
                  type: string
                  description: Description of the task
                task_difficulty:
                  type: integer
                  description: Difficulty level of the task (e.g., 1 for Easy, 2 for Medium, 3 for Hard)
      responses:
        '201':
          description: Task successfully created
        '400':
          description: Error has occurred, task creation unsuccessful

  /complete:
    post:
      description: Completes a task.
      operationId: app.complete
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - uuid
                - completed_by  # Updated to include completed_by in required fields
              properties:
                task_name:
                  type: string
                  description: Name of the task being completed
                uuid:
                  type: string
                  format: uuid
                  description: Unique UUID for the task
                completed_at:
                  type: string
                  format: date-time
                  description: Timestamp of when the task was completed
                completion_status:
                  type: boolean
                  description: Status of the task (true = complete)
                completed_by:
                  type: string
                  description: Username of the person who completed the task
                task_difficulty:
                  type: integer
                  description: Difficulty level of the task (if applicable)
      responses:
        '200':
          description: Task successfully completed 
        '400':
          description: Error has occurred, task completion unsuccessful
